apiVersion: v1
kind: Pod
metadata:
  name: volpod
spec:
  volumes:
  - name: data 
    persistentVolumeClaim:
      claimName: pvc-prem 
  containers:
  - name: ubuntu-ctr
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 3600"]
    volumeMounts:
    - name: data 
      mountPath: /data 