apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: rbnrao/kubia:latest
        # CRITICAL: Prevent K8s from trying to pull from a remote registry
        imagePullPolicy: IfNotPresent 
